### ISSUE TITLE
org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:79 in java.io.InputStreamReader@42215d80) 

### ISSUE THREAD

**Issue by gandulf** [gandulf/DsaTab#234]
``` bash
org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:79 in java.io.InputStreamReader@42215d80) 
    at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1210)
    at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1392)
    at org.kxml2.io.KXmlParser.next(KXmlParser.java:390)
    at org.kxml2.io.KXmlParser.next(KXmlParser.java:310)
    at com.dsatab.data.HeroFileInfo.readData(HeroFileInfo.java:213)
    at com.dsatab.data.HeroFileInfo.<init>(HeroFileInfo.java:111)
    at com.dsatab.cloud.HeroExchange.getHeroesByType(HeroExchange.java:403)
    at com.dsatab.cloud.HeroExchange.getHeroes(HeroExchange.java:375)
    at com.dsatab.cloud.HeroesSyncTask.loadInBackground(HeroesSyncTask.java:64)
    at com.dsatab.cloud.HeroesSyncTask.loadInBackground(HeroesSyncTask.java:13)
    at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
    at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
    at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)

```

**Comment by ninghaidong** [comment]
unterminated entity ref (position:TEXT @59:93 in java.io.StringReader@532465b8)  :  : unterminated entity ref (position:TEXT @59:93 in java.io.StringReader@532465b8)
