### ISSUE TITLE
java.lang.RuntimeException: Client initialization failed: dropbox_client_init: System error: init.cpp:132: mkdir /dD/files: No such file or directory

### ISSUE THREAD

**Issue by gandulf** [gandulf/DsaTab#279]
``` bash
java.lang.RuntimeException: Client initialization failed: dropbox_client_init: System error: init.cpp:132: mkdir /dD/files: No such file or directory
    at com.dropbox.sync.android.DbxAccount.getClient(DbxAccount.java:270)
    at com.dropbox.sync.android.DbxFileSystem.forAccount(DbxFileSystem.java:271)
    at com.dsatab.cloud.HeroExchange.uploadToDropbox(HeroExchange.java:178)
    at com.dsatab.cloud.HeroExchange.upload(HeroExchange.java:164)
    at com.dsatab.fragment.HeroChooserFragment$HeroesActionMode.onActionItemClicked(HeroChooserFragment.java:142)
    at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onActionItemClicked(PhoneWindow.java:3172)
    at com.android.internal.app.WindowDecorActionBar$ActionModeImpl.onMenuItemSelected(WindowDecorActionBar.java:1064)
    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
    at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:587)
    at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:141)
    at android.view.View.performClick(View.java:4756)
    at android.view.View$PerformClick.run(View.java:19749)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5221)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: com.dropbox.sync.android.NativeException: dropbox_client_init: System error: init.cpp:132: mkdir /dD/files: No such file or directory
    at com.dropbox.sync.android.NativeClient.throwNativeException(NativeClient.java:898)
    at com.dropbox.sync.android.NativeClient.nativeInit(Native Method)
    at com.dropbox.sync.android.NativeClient.doInitialize(NativeClient.java:291)
    at com.dropbox.sync.android.NativeClient.<init>(NativeClient.java:266)
    at com.dropbox.sync.android.DbxFileSystem.doInitialize(DbxFileSystem.java:298)
    at com.dropbox.sync.android.DbxFileSystem.<init>(DbxFileSystem.java:290)
    at com.dropbox.sync.android.DbxFileSystem.<init>(DbxFileSystem.java:47)
    at com.dropbox.sync.android.DbxFileSystem$Factory.create(DbxFileSystem.java:246)
    at com.dropbox.sync.android.DbxFileSystem$Factory.create(DbxFileSystem.java:236)
    at com.dropbox.sync.android.DbxAccount.getClient(DbxAccount.java:264)
    ... 22 more

```

**Comment by mnill** [comment]
How do u solved this issue?
